version: "3.2"

services:
  db:
    image: postgres:14
    restart: always
    container_name: url-shortener-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    restart: unless-stopped
    ports:
      - 5000:5000
    container_name: url-shortener-app
    build: .
    env_file:
      - .env.production
    depends_on:
      - db
